"""create initial DealSage schema"""
from alembic import op
import sqlalchemy as sa
revision = 'e5995a7a1b19'
down_revision = None
branch_labels = None
depends_on = None
def upgrade(): # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('doing_business_as', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('employee_range', sa.String(length=60), nullable=True),
    sa.Column('revenue_range', sa.String(length=60), nullable=True),
    sa.Column('ownership_type', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_legal_name'), 'businesses', ['legal_name'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=30), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('approximate_birth_year', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_last_name'), 'people', ['last_name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('publisher', sa.String(length=160), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('reliability', sa.String(length=30), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transition_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('published_name', sa.String(length=200), nullable=False),
    sa.Column('possible_transition_date', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relatives', sa.JSON(), nullable=False),
    sa.Column('occupation_clues', sa.JSON(), nullable=False),
    sa.Column('business_clues', sa.JSON(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transition_signals_signal_type'), 'transition_signals', ['signal_type'], unique=False)
    op.create_table('candidate_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('owner_business_confidence', sa.Integer(), nullable=False),
    sa.Column('signal_identity_confidence', sa.Integer(), nullable=False),
    sa.Column('overall_candidate_confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('match_explanation', sa.Text(), nullable=False),
    sa.Column('positive_signals', sa.JSON(), nullable=False),
    sa.Column('conflicting_signals', sa.JSON(), nullable=False),
    sa.Column('missing_evidence', sa.JSON(), nullable=False),
    sa.Column('recommended_next_action', sa.Text(), nullable=False),
    sa.Column('last_researched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['business_relationships.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['transition_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_matches_overall_candidate_confidence'), 'candidate_matches', ['overall_candidate_confidence'], unique=False)
    op.create_index(op.f('ix_candidate_matches_status'), 'candidate_matches', ['status'], unique=False)
    op.create_table('ai_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_candidate_id'), 'audit_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('normalized_facts', sa.JSON(), nullable=False),
    sa.Column('extractor_type', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_strength', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_matches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_candidate_id'), 'evidence', ['candidate_id'], unique=False)
    op.create_table('review_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('analyst_notes', sa.JSON(), nullable=False),
    sa.Column('decision_reason_codes', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    # ### end Alembic commands ###
def downgrade(): # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_evidence_candidate_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_candidate_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('ai_executions')
    op.drop_index(op.f('ix_candidate_matches_status'), table_name='candidate_matches')
    op.drop_index(op.f('ix_candidate_matches_overall_candidate_confidence'), table_name='candidate_matches')
    op.drop_table('candidate_matches')
    op.drop_index(op.f('ix_transition_signals_signal_type'), table_name='transition_signals')
    op.drop_table('transition_signals')
    op.drop_table('business_relationships')
    op.drop_table('sources')
    op.drop_index(op.f('ix_people_last_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_legal_name'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
