import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Bookmark,FolderPlus,Search,Trash2} from 'lucide-react';
import {FormEvent,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client';
import {fmt,Score,Status} from '../components/Status';
import '../watchlists.css';

export function Watchlists(){
  const qc=useQueryClient();
  const [name,setName]=useState(''),[description,setDescription]=useState(''),[candidateByList,setCandidateByList]=useState<Record<number,string>>({});
  const {data:lists=[]}=useQuery({queryKey:['watchlists'],queryFn:()=>api<any[]>('/watchlists')});
  const {data:saved=[]}=useQuery({queryKey:['saved-research'],queryFn:()=>api<any[]>('/saved-research')});
  const {data:candidates}=useQuery({queryKey:['watchlist-candidates'],queryFn:()=>api<any>('/candidates?page_size=100&sort=updated&order=desc')});
  const refresh=()=>qc.invalidateQueries({queryKey:['watchlists']});
  const create=useMutation({mutationFn:()=>api('/watchlists',{method:'POST',body:JSON.stringify({name,description:description||null})}),onSuccess:()=>{setName('');setDescription('');refresh()}});
  const add=useMutation({mutationFn:({listId,candidateId}:{listId:number,candidateId:number})=>api(`/watchlists/${listId}/candidates`,{method:'POST',body:JSON.stringify({candidate_id:candidateId,rationale:'Added from the Watchlists workspace.'})}),onSuccess:refresh});
  const remove=useMutation({mutationFn:({listId,candidateId}:{listId:number,candidateId:number})=>api(`/watchlists/${listId}/candidates/${candidateId}`,{method:'DELETE'}),onSuccess:refresh});
  const deleteSaved=useMutation({mutationFn:(id:number)=>api(`/saved-research/${id}`,{method:'DELETE'}),onSuccess:()=>qc.invalidateQueries({queryKey:['saved-research']})});
  const submit=(event:FormEvent)=>{event.preventDefault();create.mutate()};
  const query=(criteria:any)=>{const params=new URLSearchParams();Object.entries(criteria).forEach(([key,value])=>{if(value!==''&&value!=null)params.set(key,String(value))});return `/candidates?${params}`};
  return <><div className="page-heading compact"><div><p className="eyebrow">Analyst-owned workflow</p><h1>Watchlists & saved research</h1><p>Organize reviewed candidates without copying or changing their evidence.</p></div></div><div className="workflow-grid"><section className="panel"><div className="panel-title"><div><h2>Saved research</h2><p>Replay named candidate-queue criteria.</p></div><Search/></div>{saved.length?saved.map((view:any)=><div className="saved-row" key={view.id}><div><b>{view.name}</b><small>{Object.entries(view.criteria).map(([k,v])=>`${k}: ${v}`).join(' · ')||'All candidates'}</small></div><Link to={query(view.criteria)}>Run search</Link><button aria-label={`Delete ${view.name}`} onClick={()=>deleteSaved.mutate(view.id)}><Trash2/></button></div>):<p className="muted">Save criteria from the candidate queue to reuse them here.</p>}</section><section className="panel"><div className="panel-title"><div><h2>Create watchlist</h2><p>Collections belong to your signed-in identity.</p></div><FolderPlus/></div><form className="inline-form" onSubmit={submit}><input required minLength={3} placeholder="Watchlist name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Purpose or review cadence" value={description} onChange={e=>setDescription(e.target.value)}/><button className="primary" type="submit" disabled={create.isPending}>Create</button></form>{create.error&&<p className="error">{create.error.message}</p>}</section></div><div className="watchlist-stack">{lists.map((list:any)=><section className="panel" key={list.id}><div className="panel-title"><div><h2><Bookmark/> {list.name}</h2><p>{list.description||'No description'} · {list.candidates.length} candidates</p></div><div className="watchlist-add"><select aria-label={`Candidate for ${list.name}`} value={candidateByList[list.id]||''} onChange={e=>setCandidateByList({...candidateByList,[list.id]:e.target.value})}><option value="">Add a candidate…</option>{candidates?.items.map((candidate:any)=><option key={candidate.id} value={candidate.id}>{candidate.business} — {candidate.owner}</option>)}</select><button disabled={!candidateByList[list.id]} onClick={()=>add.mutate({listId:list.id,candidateId:Number(candidateByList[list.id])})}>Add</button></div></div>{list.candidates.length?<div className="watchlist-candidates">{list.candidates.map((candidate:any)=><div key={candidate.id}><div><Link to={`/candidates/${candidate.id}`}><b>{candidate.business}</b></Link><span>{candidate.owner} · {candidate.city}, {candidate.state} · added {fmt(candidate.added_at)}</span></div><Score value={candidate.overall_candidate_confidence}/><Status value={candidate.status}/><button aria-label={`Remove ${candidate.business}`} onClick={()=>remove.mutate({listId:list.id,candidateId:candidate.id})}><Trash2/></button></div>)}</div>:<p className="muted">No candidates have been added.</p>}</section>)}</div></>
}
